### ISSUE TITLE
Extension does not work for German Amazon

### ISSUE THREAD

**Issue by quassy** [amazon-alternatives/extension#71]
Even though it seems to be supported by the extension and the article is available in one of the integrated stores, the integration of “buy elsewhere“ does not happen when seeing the article on amazon.de (for all articles I tested). For example a quite popular book “Becoming” is [clearly available at buchhandel.de](https://www.buchhandel.de/suche/ergebnisse?query=becoming) but nothing different is displayed when visiting the [German Amazon listing](https://www.amazon.de/Becoming-English-Michelle-Obama/dp/1524763136/). In contrast the [US Amazon listing](https://www.amazon.com/Becoming-English-Michelle-Obama/dp/1524763136/) displays a “buy elsewhere” button with different buying options.

Tested with Firefox & Chrome extension on macOS Catalina.

**Comment by adriantombu** [comment]
I found the problem ! The German Amazon has a separate category for books in foreign langage and I wasn't handling it in the extension, so that's why there was no alternatives button.

There's still another small problem, buchhandel.de doesn't sell that book with the same ISBN than the one present on Amazon, so you won't find it there with the ISBN search I do with the extension. But it's present in the other two alternatives buchkatalog.at & genialokal.de 😀 There's not much about that I can do for now unfortunately.

I'm pushing the fix, it should be available today on Firefox and later on Chrome, I just had to check some boxes for their privacy settings and it's under validation (which could take a week or two).

**Comment by adriantombu** [comment]
Fixed here https://github.com/amazon-alternatives/extension/commit/3ae450c1017f2952bc7d79c7c40f785131dc05ff

**Comment by quassy** [comment]
I'm not sure this is the root of the problem or the only issue, because even for German language books it does not work for me: See for example this German [book about our Kaiser](https://www.amazon.de/Franz-Beckenbauer-Kleine-Anekdoten-Fu%C3%9Fballikone/dp/3742312251/) which is also available with the same ISBN-13 [on buchhandel.de](https://www.buchhandel.de/buch/Franz-Beckenbauer-9783742312259). In fact I can't seem to find any article on German Amazon where the integration is displayed, do you have an example listing which works for you?

**Comment by adriantombu** [comment]
Damn, they used yet another category (`books-catalog` instead of the simple `books` used elsewhere) 😂

**Comment by adriantombu** [comment]
Ok it looks like the only categories used for the books in amazon.de are `BOOKS_INTL_DE` and `BOOKS_CATALOG` so I removed the other ones https://github.com/amazon-alternatives/extension/commit/8c591536a21f3df72b9da2595391992503b2a422
